src/Entity/Kid.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\KidRepository")
 */
class Kid
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank()
    */
    private $kid_name;

    /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank()
    */
    private $kid_surname;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\NotBlank()
     * @Assert\Type("\DateTime")
     */
    private $kid_birthday;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\School", inversedBy="school_kid_list")
     */
    private $kid_school_id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Member", mappedBy="member_kid_list", cascade={"persist"})
     * @Assert\NotBlank()
     */
    private $kid_parent_list;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gender")
     * @ORM\JoinColumn(nullable=false)
     */
    private $kid_gender;

    public function __construct()
    {
        $this->kid_parent_list = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getKidName(): ?string
    {
        return $this->kid_name;
    }

    public function setKidName(string $kid_name): self
    {
        $this->kid_name = $kid_name;

        return $this;
    }

    public function getKidSurname(): ?string
    {
        return $this->kid_surname;
    }

    public function setKidSurname(string $kid_surname): self
    {
        $this->kid_surname = $kid_surname;

        return $this;
    }

    public function getKidBirthday(): ?\DateTimeInterface
    {
        return $this->kid_birthday;
    }

    public function setKidBirthday(?\DateTimeInterface $kid_birthday): self
    {
        $this->kid_birthday = $kid_birthday;

        return $this;
    }

    public function getKidSchoolId(): ?School
    {
        return $this->kid_school_id;
    }

    public function setKidSchoolId(?School $kid_school_id): self
    {
        $this->kid_school_id = $kid_school_id;

        return $this;
    }

    /**
     * @return Collection|Member[]
     */
    public function getKidParentList(): Collection
    {
        return $this->kid_parent_list;
    }

    public function addKidParentList(Member $kidParentList): self
    {
        if (!$this->kid_parent_list->contains($kidParentList)) {
            $this->kid_parent_list[] = $kidParentList;
            $kidParentList->addMemberKidList($this);
        }

        return $this;
    }

    public function setKidParentList(Member $kidParentList): self
    {
        return $this->addKidParentList($kidParentList);
    }

    public function removeKidParentList(Member $kidParentList): self
    {
        if ($this->kid_parent_list->contains($kidParentList)) {
            $this->kid_parent_list->removeElement($kidParentList);
            $kidParentList->removeMemberKidList($this);
        }

        return $this;
    }

    public function getKidGender(): ?Gender
    {
        return $this->kid_gender;
    }

    public function setKidGender(?Gender $kid_gender): self
    {
        $this->kid_gender = $kid_gender;

        return $this;
    }

    public function getKidAge()
    {
        $dateInterval = $this->kid_birthday->diff(new \DateTime());
        $age=(($dateInterval->y)*12)+ ($dateInterval->m);
 
        return $age;
    }

        public function getKidSizeCode()
    {
        if ($this->getKidAge()<12)
        {
            $sizeCode=(str_pad($this->getKidAge(),2,"0",STR_PAD_LEFT)).'M';
        }
        if ($this->getKidAge()>12)
        {
            $sizeCode=(str_pad(floor($this->getKidAge()/12),2,"0",STR_PAD_LEFT)).'A';
        }
        return $sizeCode;
    }

}

src/Entity/Member.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MemberRepository")
 */
// * @UniqueEntity("member_email")
class Member
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $member_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $member_surname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $member_address1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $member_address2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $member_zip_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $member_city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $member_tel;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    //unique=true
     //* @Assert\Email(
     //*      message="L'email {{ value }}  n'est pas au bon format.")
    private $member_email;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank()
     */
    private $member_password;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $member_button_wallet;

    /**
     * @ORM\Column(type="boolean")
     */
    private $member_subscription;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $member_expertise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $member_level;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Kid", inversedBy="kid_parent_list", cascade={"persist"})
     */
    private $member_kid_list;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $member_kid_count;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Workshop", mappedBy="workshop_trainer")
     */
    private $member_worshopAsTrainer;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Workshop", mappedBy="workshop_trainees_list", cascade={"persist"})
     */
    private $member_worshopAsTrainee;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DonationBag", mappedBy="donationBag_donator")
     */
    private $member_donationBag_list;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DeliveryBag", mappedBy="deliveryBag_buyer")
     */
    private $member_deliveryBag_list;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role")
     */
    private $member_role;

    public function __construct()
    {
        $this->member_kid_list = new ArrayCollection();
        $this->member_worshopAsTrainer = new ArrayCollection();
        $this->member_worshopAsTrainee = new ArrayCollection();
        $this->member_donationBag_list = new ArrayCollection();
        $this->member_deliveryBag_list = new ArrayCollection();
        $this->member_role = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getMemberName(): ?string
    {
        return $this->member_name;
    }

    public function setMemberName(string $member_name): self
    {
        $this->member_name = $member_name;

        return $this;
    }

    public function getMemberSurname(): ?string
    {
        return $this->member_surname;
    }

    public function setMemberSurname(string $member_surname): self
    {
        $this->member_surname = $member_surname;

        return $this;
    }

    public function getMemberAddress1(): ?string
    {
        return $this->member_address1;
    }

    public function setMemberAddress1(?string $member_address1): self
    {
        $this->member_address1 = $member_address1;

        return $this;
    }

    public function getMemberAddress2(): ?string
    {
        return $this->member_address2;
    }

    public function setMemberAddress2(?string $member_address2): self
    {
        $this->member_address2 = $member_address2;

        return $this;
    }

    public function getMemberZipCode(): ?string
    {
        return $this->member_zip_code;
    }

    public function setMemberZipCode(?string $member_zip_code): self
    {
        $this->member_zip_code = $member_zip_code;

        return $this;
    }

    public function getMemberCity(): ?string
    {
        return $this->member_city;
    }

    public function setMemberCity(?string $member_city): self
    {
        $this->member_city = $member_city;

        return $this;
    }

    public function getMemberTel(): ?string
    {
        return $this->member_tel;
    }

    public function setMemberTel(?string $member_tel): self
    {
        $this->member_tel = $member_tel;

        return $this;
    }

    public function getMemberEmail(): ?string
    {
        return $this->member_email;
    }

    public function setMemberEmail(string $member_email): self
    {
        $this->member_email = $member_email;

        return $this;
    }

    public function getMemberPassword(): ?string
    {
        return $this->member_password;
    }

    public function setMemberPassword(string $member_password): self
    {
        $this->member_password = $member_password;

        return $this;
    }

    public function getMemberButtonWallet(): ?int
    {
        return $this->member_button_wallet;
    }

    public function setMemberButtonWallet(?int $member_button_wallet): self
    {
        $this->member_button_wallet = $member_button_wallet;

        return $this;
    }

    public function getMemberSubscription(): ?bool
    {
        return $this->member_subscription;
    }

    public function setMemberSubscription(bool $member_subscription): self
    {
        $this->member_subscription = $member_subscription;

        return $this;
    }

    public function getMemberExpertise(): ?string
    {
        return $this->member_expertise;
    }

    public function setMemberExpertise(?string $member_expertise): self
    {
        $this->member_expertise = $member_expertise;

        return $this;
    }

    public function getMemberLevel(): ?string
    {
        return $this->member_level;
    }

    public function setMemberLevel(?string $member_level): self
    {
        $this->member_level = $member_level;

        return $this;
    }

    /**
     * @return Collection|Kid[]
     */
    public function getMemberKidList(): Collection
    {
        return $this->member_kid_list;
    }

    public function addMemberKidList(Kid $memberKidList): self
    {
        if (!$this->member_kid_list->contains($memberKidList)) {
            $this->member_kid_list[] = $memberKidList;
        }

        return $this;
    }

    public function removeMemberKidList(Kid $memberKidList): self
    {
        if ($this->member_kid_list->contains($memberKidList)) {
            $this->member_kid_list->removeElement($memberKidList);
        }

        return $this;
    }

    public function getMemberKidCount(): ?int
    {
        return $this->member_kid_count;
    }

    public function setMemberKidCount(int $member_kid_count): self
    {
        $this->member_kid_count = $member_kid_count;

        return $this;
    }

    /**
     * @return Collection|Workshop[]
     */
    public function getMemberWorshopAsTrainer(): Collection
    {
        return $this->member_worshopAsTrainer;
    }

    public function addMemberWorshopAsTrainer(Workshop $memberWorshopAsTrainer): self
    {
        if (!$this->member_worshopAsTrainer->contains($memberWorshopAsTrainer)) {
            $this->member_worshopAsTrainer[] = $memberWorshopAsTrainer;
            $memberWorshopAsTrainer->setWorkshopTrainer($this);
        }

        return $this;
    }

    public function removeMemberWorshopAsTrainer(Workshop $memberWorshopAsTrainer): self
    {
        if ($this->member_worshopAsTrainer->contains($memberWorshopAsTrainer)) {
            $this->member_worshopAsTrainer->removeElement($memberWorshopAsTrainer);
            // set the owning side to null (unless already changed)
            if ($memberWorshopAsTrainer->getWorkshopTrainer() === $this) {
                $memberWorshopAsTrainer->setWorkshopTrainer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Workshop[]
     */
    public function getMemberWorshopAsTrainee(): Collection
    {
        return $this->member_worshopAsTrainee;
    }

    public function addMemberWorshopAsTrainee(Workshop $memberWorshopAsTrainee): self
    {
        if (!$this->member_worshopAsTrainee->contains($memberWorshopAsTrainee)) {
            $this->member_worshopAsTrainee[] = $memberWorshopAsTrainee;
            $memberWorshopAsTrainee->addWorkshopTraineesList($this);
        }

        return $this;
    }

    public function removeMemberWorshopAsTrainee(Workshop $memberWorshopAsTrainee): self
    {
        if ($this->member_worshopAsTrainee->contains($memberWorshopAsTrainee)) {
            $this->member_worshopAsTrainee->removeElement($memberWorshopAsTrainee);
            $memberWorshopAsTrainee->removeWorkshopTraineesList($this);
        }

        return $this;
    }

    /**
     * @return Collection|DonationBag[]
     */
    public function getMemberDonationBagList(): Collection
    {
        return $this->member_donationBag_list;
    }

    public function addMemberDonationBagList(DonationBag $memberDonationBagList): self
    {
        if (!$this->member_donationBag_list->contains($memberDonationBagList)) {
            $this->member_donationBag_list[] = $memberDonationBagList;
            $memberDonationBagList->setDonationBagDonator($this);

src/Form/MemberType.php
<?php

namespace App\Form;

use App\Entity\Member;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Form\KidType;

class MemberType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('memberName', TextType::class, array('label'  => 'Nom :'))
            ->add('memberSurname', TextType::class, array('label'  => 'Prénom :'))
            ->add('memberAddress1', TextType::class, array('label'  => 'Adresse :'))
            ->add('memberAddress2', TextType::class, array('label'  => 'Adresse (complément) :'))
            ->add('memberZipCode', TextType::class, array('label'  => 'Code Postal :'))
            ->add('memberCity', TextType::class, array('label'  => 'Ville :'))
            ->add('memberTel', TelType::class, array('label'  => 'Téléphone :'))
            ->add('memberEmail', EmailType::class, array('label'  => 'email :'))
            ->add('memberPassword', PasswordType::class, array('label'  => 'Mot de passe :'))
            ->add('memberButtonWallet', HiddenType::class, array('data'  => '0'))
            // ->add('memberRole', HiddenType::class, array('data'  => 'visiteur'))
            ->add('memberKidCount',IntegerType::class, array('label'  => 'Nombre d\'enfants :'))
            ->add('memberSubscription', ChoiceType::class, array(
                'label'  => 'Abonnement à la newsletter',
                'expanded'=> true,
                'choices' => array(
                    'Oui' => true,
                    'Non' => false
                )))
            ->add('memberExpertise', TextType::class, array('label'  => 'Compétence que vous pouvez mettre à disposition:'))
            ->add('memberLevel', RangeType::class, array('label'  => 'Niveau en couture:'))
            ->add('memberKidList', CollectionType::class, array(
                    'label'  => 'Enfant :',
                    'entry_type' => KidType::class,
                    'allow_add'=> true,
                    'allow_delete' => true
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Member::class,
        ]);
    }
}
        

templates/member/_delete_form.html.twig
<form method="post" action="{{ path('member_delete', {'id': member.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer ce profil?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ member.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/member/_form.html.twig
{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
   mais si vous l'avez en local, changez simplement l'adresse. #}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

{# Voici le script en question : #}
<script type="text/javascript">
  $(document).ready(function() {
    // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
    var $container = $('div#member_memberKidList');

    // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
    var index = $container.find(':input').length;
    
    // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
    $('#add_kid').click(function(e) {
      addKid($container);

      e.preventDefault(); // évite qu'un # apparaisse dans l'URL
      return false;
    });

    // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'un nouveau membre par exemple).
    {# if (index == 0) {
      addKid($container);
    } else {
      // S'il existe déjà des enfants, on ajoute un lien de suppression pour chacune d'entre elles
      $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    } #}

    // La fonction qui ajoute un formulaire KidType
    function addKid($container) {
      // Dans le contenu de l'attribut « data-prototype », on remplace :
      // - le texte "__name__label__" qu'il contient par le label du champ
      // - le texte "__name__" qu'il contient par le numéro du champ
      var template = $container.attr('data-prototype')
        .replace(/__name__label__/g, 'Enfant n°' + (index+1))
        .replace(/__name__/g,        index)
      ;

      // On crée un objet jquery qui contient ce template
      var $prototype = $(template);

      // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
      addDeleteLink($prototype);

      // On ajoute le prototype modifié à la fin de la balise <div>
      $container.append($prototype);

      // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
      index++;
    }

    // La fonction qui ajoute un lien de suppression d'une catégorie
    function addDeleteLink($prototype) {
      // Création du lien
      var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

      // Ajout du lien
      $prototype.append($deleteLink);

      // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
      $deleteLink.click(function(e) {
        $prototype.remove();

        e.preventDefault(); // évite qu'un # apparaisse dans l'URL
        return false;
      });
    }
  });
</script>


{{ form_start(form) }}
  
    {{ form_widget(form) }}
        {{ form_row(form.memberName) }}
        {{ form_row(form.memberSurname) }}
        {{ form_row(form.memberAddress1) }}
        {{ form_row(form.memberAddress2) }}
        {{ form_row(form.memberZipCode) }}
        {{ form_row(form.memberCity) }}
        {{ form_row(form.memberTel) }}
        {{ form_row(form.memberEmail) }}
        {{ form_row(form.memberPassword) }}
        {{ form_row(form.memberKidCount) }}
        {{ form_row(form.memberSubscription, {label_attr: {class: 'radio-custom'} }) }}
        {{ form_row(form.memberExpertise) }}
        {{ form_row(form.memberLevel) }}
        {{ form_row(form.memberKidList) }}
        <a href="#" id="add_kid" class="btn btn-secondary">Inscrire un enfant</a>
        <a href="#" id="addDeleteLink" class="btn btn-secondary">Désinscrire un enfant</a>
        <br>
        <br>
    <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/member/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier votre profil{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier votre profil</h1>
        <form class="form-group" method="post">
        {{ include('member/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        </form>
        <a href="{{ path('member_index') }}">Retour à la liste</a>
        <br>
        {{ include('member/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/member/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des membres{% endblock %}

{% block body %}
    <h1>Liste des membres</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                {# <th>Adresse (1)</th>
                <th>Adresse (2)</th>
                <th>Code Postal</th>
                <th>Ville</th> #}
                <th>Tel</th>
                <th>Email</th>
                <th>Souscription Newsletter</th>
                <th>Niveau en couture</th>
                <th>Montant Cagnotte</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for member in members %}
            <tr>
                <td>{{ member.memberName }}</td>
                <td>{{ member.memberSurname }}</td>
                {# <td>{{member.memberAddress1}}</td>
                <td>{{member.memberAddress2}}</td>
                <td>{{member.memberZipCode}}</td>
                <td>{{member.memberCity}}</td> #}
                <td>{{member.memberTel}}</td>
                <td>{{member.memberEmail}}</td>
                <td>{{member.memberSubscription}}</td>
                <td>{{member.memberLevel}}</td>
                <td>{{member.memberButtonWallet}}</td>
                <td>
                    <a href="{{ path('member_show', {'id': member.Id}) }}">voir la fiche - </a>
                    <a href="{{ path('member_edit', {'id': member.id}) }}"> éditer la fiche</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">Aucun membre trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('member_new') }}">Créer un nouveau membre</a>
    <a href="{{ path('member_admin') }}">Retour au menu Admin</a>
{% endblock %}

templates/member/memberAdmin.html.twig
{% extends 'base.html.twig'%}

{% block body %}


<h1>Menu ADMIN </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Données :</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Articles</td>
                <td>
                    <a href="{{ path('article_index') }}">voir la liste</a> 
                </td>
            </tr>
            <tr>
                <td>Membres</td>
                <td>
                    <a href="{{ path('member_index') }}">voir la liste</a>
                </td>
            </tr>
            <tr>
                <td>Sacs de dons</td>
                <td>
                    <a href="{{ path('donation_bag_index') }}">voir la liste</a>
                </td>
            </tr>
            <tr>
                <td>Sacs de livraison</td>
                <td>
                    <a href="{{ path('delivery_bag_index') }}">voir la liste</a>  
                </td>
            </tr>
            <tr>
                <td>Tournées des écoles</td>
                <td>
                    <a href="{{ path('school_stop_index') }}">voir la liste</a> 
                </td>
            </tr>
            <tr>
                <td>News</td>
                <td>
                    <a href="{{ path('news_index') }}">voir la liste</a> 
                </td>
            </tr>
            <tr>
                <td>Ateliers</td>
                <td>
                    <a href="{{ path('workshop_index') }}">voir la liste</a> 
                </td>
            </tr>
        </tbody>
    </table>

{% endblock %}

templates/member/memberConnect.html.twig
{% extends 'base.html.twig'%}
{% block title %}Troc&Mode Kids{% endblock %}

{% block body %}
    <div class="container">
        <div>
            <h1>Me connecter</h1>
            <form class="form-group" method="post">
                {{ form_start(form) }}
                {{ form_widget(form) }}
                {{ form_end(form) }}
            </form>
        </div>
        <div>
        <a href="{{ path('member_new')}}" class="btn btn-secondary">Pas encore inscrit ?</a>
        </div>
        <br>
    </div>
{% endblock %}

templates/member/memberShow.html.twig
{% extends 'base.html.twig'%}

{% block body %}
<div class="container">
    <h1>Votre profil</h1>

<div class="row">
    <div class = "col-lg-6 mb-6">
        <table class="table">
            <thead>
                <th> Vous
                </th>
            </thead>
            <tbody>
                <tr>
                    <td>{{member.memberSurname}} {{member.memberName}}</td>
                </tr>
                <tr>
                    <td>{{member.memberAddress1}}<br>{{member.memberAddress2}}</td>
                </tr>
                <tr>
                    <td>{{member.memberZipCode}} {{member.memberCity}}</td>
                </tr>
                <tr>
                    <td>Tel : {{member.memberTel}}</td>
                </tr>
                <tr>
                    <td>Email : {{member.memberEmail}}</td>
                </tr>
                <tr>
                    <td> Abonnement à la newsletter :
                    {% if member.memberSubscription == true %}
                        <p>oui</p>
                    {% else %}
                        <p>non</p>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td> Niveau de couture :{{member.memberLevel}}/100
                    </td>
                </tr>
                <tr>
                    <td>Cagnotte : {{member.memberButtonWallet}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class = "col-lg-6 mb-6">
        {% if member.memberKidList %}
            <table>
                <tbody>
                    <thead>
                        <th> Votre(vos) enfant(s)</th>
                    </thead>
                {% for kid in member.memberKidList %}
                    <tr>
                        <td>{{kid.kidSurname}} {{kid.kidName}}</td>
                    </tr>
                    <tr>
                        <td></td>
                    </tr>
                    <tr>
                        <td>{{kid.kidGender.GenderName}}</td>
                    </tr>
                    <tr>
                        <td>{{kid.kidBirthday | date ('d-m-Y')}}</td>
                    </tr>
                    <tr>
                        <td>Ecole : {{kid.kidSchoolId.SchoolName}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

</div>

        {# <form class="form-group" method="post">
        {{ include('member/_form.html.twig') }}
        </form>
        <a href="{{ path('home_index') }}">Retour à l'accueil</a>
        <br>
        {{ include('member/_delete_form.html.twig') }} #}

<div class="row" style="text-align:justify">
    
        <a class="btn btn-secondary" href="/member/unsetSession">Me déconnecter</a>
        <p>             </p>
        <a class="btn btn-secondary" href="{{ path('member_edit', {'id': member.id})}}">Modifier mon profil</a>
        <p>   </p>
        <a class="btn btn-secondary" href="/donationBag/show">Voir mes derniers dons</a>
        <p>   </p>
        <a class="btn btn-secondary" href="/deliveryBag/show">Voir mes dernières trouvailles</a>
    
</div>
        <br>
        {% if app.session.get('user') %}
            {% for role in app.session.get('user').MemberRole %}
                {% if role.id ==  "6" %}
                <a href="{{ path('member_edit', {'id': member.id}) }}">Modifier</a>
                <br>
                {{ include('member/_delete_form.html.twig') }}
                {% endif %}
            {% endfor %}
        {% endif %} 

    </div>
{% endblock %}