src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $article_picture1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $article_picture2;

    // Picture 3 not used yet
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    // private $article_picture3;

    /**
     * @ORM\Column(type="float")
     */
    private $article_buttonValue;

    /**
     * @ORM\Column(type="float")
     */
    private $article_eurosValue;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $article_comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Color")
     */
    private $article_color;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Brand")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_brand;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Size")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_size;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\WearStatus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_wearStatus;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gender")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_gender;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProcessStatus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_processStatus;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Fabric", cascade={"persist"})
     */
    private $article_fabric;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DeliveryBag", inversedBy="deliveryBag_article_list")
     */
    private $article_deliveryBag;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DonationBag", inversedBy="donationBag_article_list")
     */
    private $article_donationBag;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Season")
     */
    private $article_season;

    /**
     * @ORM\Column(type="string", length=13)
     */
    private $article_code;


    public function __construct()
    {
        $this->article_color = new ArrayCollection();
        $this->article_fabric = new ArrayCollection();
        $this->article_season = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getArticlePicture1()
    {
        return $this->article_picture1;
    }

    public function setArticlePicture1( $article_picture1)  
    {
        $this->article_picture1 = $article_picture1;

        return $this;
    }

    public function getArticlePicture2()
    {
        return $this->article_picture2;
    }

    public function setArticlePicture2($article_picture2)
    {
        $this->article_picture2 = $article_picture2;

        return $this;
    }

    // Picture 3 not used yet
    // public function getArticlePicture3()
    // {
    //     return $this->article_picture3;
    // }

    // public function setArticlePicture3($article_picture3)
    // {
    //     $this->article_picture3 = $article_picture3;

    //     return $this;
    // }

    public function getArticleButtonValue(): ?float
    {
        return $this->article_buttonValue;
    }

    public function setArticleButtonValue(float $article_buttonValue): self
    {
        $this->article_buttonValue = $article_buttonValue;

        return $this;
    }

    public function getArticleEurosValue(): ?float
    {
        return $this->article_eurosValue;
    }

    public function setArticleEurosValue(float $article_eurosValue): self
    {
        $this->article_eurosValue = $article_eurosValue;

        return $this;
    }

    public function getArticleComments(): ?string
    {
        return $this->article_comments;
    }

    public function setArticleComments(?string $article_comments): self
    {
        $this->article_comments = $article_comments;

        return $this;
    }

    /**
     * @return Collection|Color[]
     */
    public function getArticleColor(): Collection
    {
        return $this->article_color;
    }

    public function addArticleColor(Color $articleColor): self
    {
        if (!$this->article_color->contains($articleColor)) {
            $this->article_color[] = $articleColor;
        }

        return $this;
    }

    public function removeArticleColor(Color $articleColor): self
    {
        if ($this->article_color->contains($articleColor)) {
            $this->article_color->removeElement($articleColor);
        }

        return $this;
    }

    public function getArticleBrand(): ?Brand
    {
        return $this->article_brand;
    }

    public function setArticleBrand(?Brand $article_brand): self
    {
        $this->article_brand = $article_brand;

        return $this;
    }

    public function getArticleType(): ?Type
    {
        return $this->article_type;
    }

    public function setArticleType(?Type $article_type): self
    {
        $this->article_type = $article_type;

        return $this;
    }

    public function getArticleSize(): ?Size
    {
        return $this->article_size;
    }

    public function setArticleSize(?Size $article_size): self
    {
        $this->article_size = $article_size;

        return $this;
    }

    public function getArticleWearStatus(): ?WearStatus
    {
        return $this->article_wearStatus;
    }

    public function setArticleWearStatus(?WearStatus $article_wearStatus): self
    {
        $this->article_wearStatus = $article_wearStatus;

        return $this;
    }

    public function getArticleGender(): ?Gender
    {
        return $this->article_gender;
    }

    public function setArticleGender(?Gender $article_gender): self
    {
        $this->article_gender = $article_gender;

        return $this;
    }

    public function getArticleProcessStatus(): ?ProcessStatus
    {
        return $this->article_processStatus;
    }

    public function setArticleProcessStatus(?ProcessStatus $article_processStatus): self
    {
        $this->article_processStatus = $article_processStatus;

        return $this;
    }

    /**
     * @return Collection|Fabric[]
     */
    public function getArticleFabric(): Collection
    {
        return $this->article_fabric;
    }

    public function addArticleFabric(Fabric $articleFabric): self
    {
        if (!$this->article_fabric->contains($articleFabric)) {
            $this->article_fabric[] = $articleFabric;
        }

        return $this;
    }

    public function removeArticleFabric(Fabric $articleFabric): self
    {
        if ($this->article_fabric->contains($articleFabric)) {
            $this->article_fabric->removeElement($articleFabric);
        }

        return $this;
    }

    public function getArticleDeliveryBag(): ?DeliveryBag
    {
        return $this->article_DeliveryBag;
    }

    public function setArticleDeliveryBag(?DeliveryBag $article_DeliveryBag): self
    {
        $this->article_DeliveryBag = $article_DeliveryBag;

        return $this;
    }

    public function getArticleDonationBag(): ?DonationBag
    {
        return $this->article_donationBag;
    }

    public function setArticleDonationBag(?DonationBag $article_donationBag): self
    {
        $this->article_donationBag = $article_donationBag;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getArticleSeason(): Collection
    {
        return $this->article_season;
    }

    public function addArticleSeason(Season $articleSeason): self
    {
        if (!$this->article_season->contains($articleSeason)) {
            $this->article_season[] = $articleSeason;
        }

        return $this;
    }

    public function removeArticleSeason(Season $articleSeason): self
    {
        if ($this->article_season->contains($articleSeason)) {
            $this->article_season->removeElement($articleSeason);
        }

        return $this;
    }

    public function getArticleCode(): ?string
    {
        return $this->article_code;
    }

    public function setArticleCode(?string $last_article_code): ?string
    {
        // We get a NUM code from the 4 last characters of the last similar article
        $numCode = substr( $last_article_code, -4 );

        // We increment this NUM code  
        if( ctype_digit($numCode) ) {
            $numCode = (int)$numCode;
            $numCode++;
            $numCode=str_pad($numCode,4,"0",STR_PAD_LEFT);
        }
       // We create a GENDER code
        $genderCode = $this->getArticleGender()->getGenderCode();
        
        // We create a SIZE code
        $sizeCode = $this->getArticleSize()->getSizeCode();

        // We create a SEASON code ( with 1 or 2 optionnal characters)
        $seasonCode='';
            foreach($this->getArticleSeason() as $articleSeason)
            {
                $seasonCode = $seasonCode.$articleSeason->getSeasonCode();
            }
        if(strlen($seasonCode)<1)
            {
                $seasonCode= ( str_pad($seasonCode ,2, "0", STR_PAD_LEFT) );
            }
        // We create a TYPE code
        $typeCode = $this->getArticleType()->getTypeCode();

        // We concatenate the differents codes
        $this->article_code = $genderCode.$sizeCode.$seasonCode.$typeCode.$numCode;
        
        return $this->article_code;
    }

}

src/Entity/Workshop.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkshopRepository")
 */
class Workshop
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $workshop_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $workshop_theme;

    /**
     * @ORM\Column(type="float")
     */
    private $workshop_fee;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $workshop_place;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $workshop_picture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Member", inversedBy="member_worshopAsTrainer")
     * @ORM\JoinColumn(nullable=false)
     */
    private $workshop_trainer;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Member", inversedBy="member_worshopAsTrainee", cascade={"persist"})
     */
    private $workshop_trainees_list;

    public function __construct()
    {
        $this->workshop_trainees_list = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getWorkshopDate(): ?\DateTimeInterface
    {
        return $this->workshop_date;
    }

    public function setWorkshopDate(\DateTimeInterface $workshop_date): self
    {
        $this->workshop_date = $workshop_date;

        return $this;
    }

    public function getWorkshopTheme(): ?string
    {
        return $this->workshop_theme;
    }

    public function setWorkshopTheme(string $workshop_theme): self
    {
        $this->workshop_theme = $workshop_theme;

        return $this;
    }

    public function getWorkshopFee(): ?float
    {
        return $this->workshop_fee;
    }

    public function setWorkshopFee(float $workshop_fee): self
    {
        $this->workshop_fee = $workshop_fee;

        return $this;
    }

    public function getWorkshopPlace(): ?string
    {
        return $this->workshop_place;
    }

    public function setWorkshopPlace(?string $workshop_place): self
    {
        $this->workshop_place = $workshop_place;

        return $this;
    }

    public function getWorkshopPicture(): ?string
    {
        return $this->workshop_picture;
    }

    public function setWorkshopPicture(?string $workshop_picture): self
    {
        $this->workshop_picture = $workshop_picture;

        return $this;
    }

    public function getWorkshopTrainer(): ?Member
    {
        return $this->workshop_trainer;
    }

    public function setWorkshopTrainer(?Member $workshop_trainer): self
    {
        $this->workshop_trainer = $workshop_trainer;

        return $this;
    }

    /**
     * @return Collection|Member[]
     */
    public function getWorkshopTraineesList(): Collection
    {
        return $this->workshop_trainees_list;
    }

    public function addWorkshopTraineesList(Member $workshopTraineesList): self
    {
        if (!$this->workshop_trainees_list->contains($workshopTraineesList)) {
            $this->workshop_trainees_list[] = $workshopTraineesList;
        }

        return $this;
    }

    public function removeWorkshopTraineesList(Member $workshopTraineesList): self
    {
        if ($this->workshop_trainees_list->contains($workshopTraineesList)) {
            $this->workshop_trainees_list->removeElement($workshopTraineesList);
        }

        return $this;
    }
}

src/Form/WorkshopType.php
<?php

namespace App\Form;

use App\Entity\Workshop;
use App\Entity\Member;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface; 
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Doctrine\ORM\EntityRepository;
use App\Form\WorkshopType;
use App\Repository\WorkshopRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class WorkshopType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('workshop_date', DateTimeType::class, array(
                'label'  => 'Date et heure :',
                'widget' => 'choice',
                // pourquoi le format n'est pas pris en compte ?
                'format' => 'dd-MM-yyyy',
                'placeholder' => array(
                        'day' => 'Jour', 'month' => 'Mois', 'year' => 'Année',)
                ))
            ->add('workshop_theme', TextType::class, array('label'  => 'Thème : '))
            ->add('workshop_fee', MoneyType::class, array('label'  => 'Prix : '))
            ->add('workshop_place', TextareaType::class, array('label'  => 'Lieu :'))
            ->add('workshop_picture', TextType::class, array('label'  => 'Image :'))
            ->add('workshop_trainer', EntityType::class, array(
                'label'  => 'Formateur',
                'class' => Member::class,
                'query_builder' => function (\App\Repository\MemberRepository $er) {
                    return $er->createQueryBuilder('m')
                        ->innerJoin('m.member_role', 'r', 'WITH', 'r.role_name = :role')
                        ->addselect('r')
                        ->orderBy('m.member_name', 'ASC')
                        ->setParameter('role', "formateur");
                 },
                'choice_label' => function ($trainers){
                 return $trainers->getMemberSurname().' '.$trainers->getMemberName();
                },
                ))
            ->add('workshop_trainees_list', EntityType::class, array(
                'label'  => 'Personnes inscrites',
                'class' => Member::class,
                'choice_label' => function ($members){
                 return $members->getMemberSurname().' '.$members->getMemberName();
                },
                'multiple'=>true
                ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Workshop::class,
        ]);
    }
}

templates/workshop/_delete_form.html.twig
<form method="post" action="{{ path('workshop_delete', {'id': workshop.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ workshop.id) }}">
    <button class="btn">Delete</button>
</form>

templates/workshop/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/workshop/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation Atelier{% endblock %}

{% block body %}
    <h1>Je réserve un atelier</h1>

    <table class="table">
        <tbody>
            {# <tr>
                <th>Id</th>
                <td>{{ workshop.id }}</td>
            </tr> #}
            <tr>
                <th>Date / Heure </th>
                <td>{{ workshop.workshopDate ? workshop.workshopDate|date('m-d-Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Thème</th>
                <td>{{ workshop.workshopTheme }}</td>
            </tr>
            <tr>
                <th>Coût</th>
                <td>{{ workshop.workshopFee }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ workshop.workshopPlace }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ workshop.workshopPicture }}</td>
            </tr>
            <tr>
                <th>Formateur</th>
                <td>{{ workshop.workshopTrainer.MemberSurname }}  {{ workshop.workshopTrainer.MemberName }}</td>
            </tr>
            {# <tr>
                <th>Workshop_trainees</th>
                {% for trainee in workshop.workshopTraineesList %}
                <td>{{trainee.MemberSurname}} {{trainee.MemberName}}</td>
                {% endfor %}
            </tr> #}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('workshop_pay', {'id': workshop.id}) }}">Je paye</a>
    <br>
    <a href="{{ path('workshop_index') }}">Retour à la liste</a>
    <br>
    
    

{% endblock %}

templates/workshop/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un atelier{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier un atelier</h1>
        <form class="form-group" method="post">
        {{ include('workshop/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        </form>
        <a href="{{ path('workshop_index') }}">Retour à la liste</a>
        <br>
        {{ include('workshop/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/workshop/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Je participe{% endblock %}

{% block body %}
<div class="container">
    <h1>Je participe</h1>
    <br>
    {% if app.session.get('user') %}
        {% for role in app.session.get('user').MemberRole %}
            {% if role.id ==  "6" %}
            <br>
            {% endif %}
        {% endfor %}
    {% else %}
    <div class="row">
        <div class="col-lg-6 mb-6">
            <img src={{ asset('images/Sewing.jpeg')}} height="400px"/>
        </div>
        <div class="col-lg-6 mb-6">
        <p>Vous êtes couturière débutante et vous avez envie d'aprrendre quelques techniques de couture ?
        Inscrivez vous à un des ateliers et découvrer comment réparer, transformer ou donner une 2ème vie à vos vêtements !
        Ou bien créer des accessoires à partir de tissus recyclés !<P>
        {# <br> #}
        <P>Vous êtes une passionnée de couture et avez envie de partager vos connaissances et vos astuces ?
        Le local de Troc & Mode est à votre disposition, gratuitement, pour vous accueillir (vous et votre machine !) et coudre avec d'autres passionnées !</p>
        <p>Du jeudi au vendredi, de 10H à 12H et 14H à 18H, au xxx, rue xxx, à Castelnau le lez.<p>
        </div>
    </div>
    {% endif %}

    <br>
    <h2>Liste des ateliers Couture</h2>
    <table class="table">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Date / Heure</th>
                <th>Thème</th>
                <th>Prix</th>
                <th>Lieu</th>
                <th>Image</th>
                <th>Formateur</th>
                    {% if app.session.get('user') %}
                        {% for role in app.session.get('user').MemberRole %}
                            {% if role.id ==  "6" %}
                            <th>Personnes inscrites</th>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for workshop in workshops %}
            <tr>
                {# <td>{{ workshop.id }}</td> #}
                <td>{{ workshop.workshopDate ? workshop.workshopDate|date('Y-m-d H:i') : '' }}</td>
                <td>{{ workshop.workshopTheme }}</td>
                <td>{{ workshop.workshopFee }}</td>
                <td>{{ workshop.workshopPlace }}</td>
                <td><img src={{ asset('images/' ~ workshop.workshopPicture)}} height="50px"/></td>
                 {# <img class="d-block w-100 img-fluid" src="{{ asset('uploads/pictures/' ~ article.articlePicture1)}}" alt="First slide"> #}
                        </div>
                {# <td>{{ workshop.workshopPicture }}</td> #}
                <td>{{ workshop.workshopTrainer.MemberSurname }} {{ workshop.workshopTrainer.MemberName }}</td>
                {% if app.session.get('user') %}
                    {% for role in app.session.get('user').MemberRole %}
                        {% if role.id ==  "6" %}
                            {% for trainee in workshop.workshopTraineesList %}
                            <td>{{trainee.MemberSurname}} {{trainee.MemberName}}</td>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <td>
                    <a href="{{ path('workshop_book', {'id': workshop.id}) }}">S'inscrire</a>
                {% if app.session.get('user') %}
                    {% for role in app.session.get('user').MemberRole %}
                        {% if role.id ==  "6" %}
                            <a href="{{ path('workshop_edit', {'id': workshop.id}) }}">Modifier la fiche</a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun atelier trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if app.session.get('user') %}
        {% for role in app.session.get('user').MemberRole %}
            {% if role.id ==  "6" %}
                <a href="{{ path('workshop_new') }}">Créer un nouvel atelier</a>
            {% endif %}
        {% endfor %}
    {% endif %}
    
</div> 
{% endblock %}

templates/workshop/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un atelier{% endblock %}

{% block body %}
    <div class="container">
        <h1>Créer un atelier</h1>
        <form class="form-group">
        {{ include('workshop/_form.html.twig', {'button_label': 'Créer'}) }}
        </form>
        <a href="{{ path('workshop_index') }}">Retour à la liste</a>
    </div>
{% endblock %}

templates/workshop/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Workshop{% endblock %}

{% block body %}
    <h1>Workshop</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ workshop.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ workshop.workshopDate ? workshop.workshopDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Thème</th>
                <td>{{ workshop.workshopTheme }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ workshop.workshopFee }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ workshop.workshopPlace }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ workshop.workshopPicture }}</td>
            </tr>
            <tr>
                <th>Formateur</th>
                <td>{{ workshop.workshopTrainer.MemberSurname }}  {{ workshop.workshopTrainer.MemberName }}</td>
            </tr>
            {% if app.session.get('user') %}
                {% for role in app.session.get('user').MemberRole %}
                    {% if role.id ==  "6" %}
                        <tr>
                        <th>Participants</th>
                        {% for trainee in workshop.workshopTraineesList %}
                        <td>{{trainee.MemberSurname}} {{trainee.MemberName}}</td>
                        {% endfor %}
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}      
        </tbody>
    </table>
    <br>
    <a href="{{ path('workshop_index') }}">Retour à la liste</a>
    <br>
    {% if app.session.get('user') %}
        {% for role in app.session.get('user').MemberRole %}
            {% if role.id ==  "6" %}
                <a href="{{ path('workshop_edit', {'id': workshop.id}) }}">modifier</a>
                <br>
                {{ include('workshop/_delete_form.html.twig') }}
            {% endif %}
        {% endfor %}
    {% endif %}  
{% endblock %}