src/Entity/School.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SchoolRepository")
 */
class School
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $school_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $school_address1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $school_address2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $school_zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $school_city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $school_director_gender;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $school_director_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $school_director_tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $school_director_email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Kid", mappedBy="kid_school_id")
     */
    private $school_kid_list;

    public function __construct()
    {
        $this->school_kid_list = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getSchoolName(): ?string
    {
        return $this->school_name;
    }

    public function setSchoolName(string $school_name): self
    {
        $this->school_name = $school_name;

        return $this;
    }

    public function getSchoolAddress1(): ?string
    {
        return $this->school_address1;
    }

    public function setSchoolAddress1(?string $school_address1): self
    {
        $this->school_address1 = $school_address1;

        return $this;
    }

    public function getSchoolAddress2(): ?string
    {
        return $this->school_address2;
    }

    public function setSchoolAddress2(?string $school_address2): self
    {
        $this->school_address2 = $school_address2;

        return $this;
    }

    public function getSchoolZipCode(): ?string
    {
        return $this->school_zip_code;
    }

    public function setSchoolZipCode(?string $school_zip_code): self
    {
        $this->school_zip_code = $school_zip_code;

        return $this;
    }

    public function getSchoolCity(): ?string
    {
        return $this->school_city;
    }

    public function setSchoolCity(string $school_city): self
    {
        $this->school_city = $school_city;

        return $this;
    }

    public function getSchoolDirectorGender(): ?string
    {
        return $this->school_director_gender;
    }

    public function setSchoolDirectorGender(string $school_director_gender): self
    {
        $this->school_director_gender = $school_director_gender;

        return $this;
    }

    public function getSchoolDirectorName(): ?string
    {
        return $this->school_director_name;
    }

    public function setSchoolDirectorName(string $school_director_name): self
    {
        $this->school_director_name = $school_director_name;

        return $this;
    }

    public function getSchoolDirectorTel(): ?string
    {
        return $this->school_director_tel;
    }

    public function setSchoolDirectorTel(?string $school_director_tel): self
    {
        $this->school_director_tel = $school_director_tel;

        return $this;
    }

    public function getSchoolDirectorEmail(): ?string
    {
        return $this->school_director_email;
    }

    public function setSchoolDirectorEmail(?string $school_director_email): self
    {
        $this->school_director_email = $school_director_email;

        return $this;
    }

    /**
     * @return Collection|Kid[]
     */
    public function getSchoolKidList(): Collection
    {
        return $this->school_kid_list;
    }

    public function addSchoolKidList(Kid $schoolKidList): self
    {
        if (!$this->school_kid_list->contains($schoolKidList)) {
            $this->school_kid_list[] = $schoolKidList;
            $schoolKidList->setKidSchoolId($this);
        }

        return $this;
    }

    public function removeSchoolKidList(Kid $schoolKidList): self
    {
        if ($this->school_kid_list->contains($schoolKidList)) {
            $this->school_kid_list->removeElement($schoolKidList);
            // set the owning side to null (unless already changed)
            if ($schoolKidList->getKidSchoolId() === $this) {
                $schoolKidList->setKidSchoolId(null);
            }
        }

        return $this;
    }
}

src/Form/SchoolType.php
<?php

namespace App\Form;

use App\Entity\School;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SchoolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('school_name')
            ->add('school_address1')
            ->add('school_address2')
            ->add('school_zip_code')
            ->add('school_city')
            ->add('school_director_gender')
            ->add('school_director_name')
            ->add('school_director_tel')
            ->add('school_director_email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => School::class,
        ]);
    }
}

src/Controller/SchoolController.php
<?php

namespace App\Controller;

use App\Entity\School;
use App\Form\SchoolType;
use App\Repository\SchoolRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class SchoolController extends Controller
{
    /**
     * @Route("/school/", name="school_index", methods="GET")
     */
    public function index(SchoolRepository $schoolRepository): Response
    {
        return $this->render('school/index.html.twig', ['schools' => $schoolRepository->findAll()]);
    }

    /**
     * @Route("/school/new", name="school_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $school = new School();
        $form = $this->createForm(SchoolType::class, $school);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($school);
            $em->flush();

            return $this->redirectToRoute('school_index');
        }

        return $this->render('school/new.html.twig', [
            'school' => $school,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/school/{id}", name="school_show", methods="GET")
     */
    public function show(School $school): Response
    {
        return $this->render('school/show.html.twig', ['school' => $school]);
    }

    /**
     * @Route("/school/{id}/edit", name="school_edit", methods="GET|POST")
     */
    public function edit(Request $request, School $school): Response
    {
        $form = $this->createForm(SchoolType::class, $school);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('school_edit', ['id' => $school->getId()]);
        }

        return $this->render('school/edit.html.twig', [
            'school' => $school,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/school/{id}", name="school_delete", methods="DELETE")
     */
    public function delete(Request $request, School $school): Response
    {
        if ($this->isCsrfTokenValid('delete'.$school->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($school);
            $em->flush();
        }

        return $this->redirectToRoute('school_index');
    }
}

templates/school/_delete_form.html.twig
<form method="post" action="{{ path('school_delete', {'id': school.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer cette école ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ school.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/school/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/school/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une école{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier les données d'une école</h1>
        <form class="form-group" method="post">
        {{ include('school/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        </form>
        <a href="{{ path('school_index') }}">Retour à la liste</a>
        <br>
        {{ include('school/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/school/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des écoles{% endblock %}

{% block body %}
    <h1>Liste des écoles</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Adresse (1)</th>
                <th>Adresse (2)</th>
                <th>Code Postal</th>
                <th>Ville</th>
                <th>Mr / Mme</th>
                <th>Directeur / Directrice</th>
                <th>Tel</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for school in schools %}
            <tr>
                <td>{{ school.id }}</td>
                <td>{{ school.schoolName }}</td>
                <td>{{ school.schoolAddress1 }}</td>
                <td>{{ school.schoolAddress2 }}</td>
                <td>{{ school.schoolZipCode }}</td>
                <td>{{ school.schoolCity }}</td>
                <td>{{ school.schoolDirectorGender }}</td>
                <td>{{ school.schoolDirectorName }}</td>
                <td>{{ school.schoolDirectorTel }}</td>
                <td>{{ school.schoolDirectorEmail }}</td>
                <td>
                    <a href="{{ path('school_show', {'id': school.id}) }}">voir la fiche - </a>
                    <a href="{{ path('school_edit', {'id': school.id}) }}">éditer la fiche </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucune école trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('school_new') }}">Create new</a>
{% endblock %}

templates/school/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'une nouvelle Ecole {% endblock %}

{% block body %}
    <div class="container">
        <h1>Créer une nouvelle école</h1>
        <form class="form-group" method="post">
        {{ include('school/_form.html.twig', {'button_label': 'Créer'}) }}
        </form>
        <a href="{{ path('school_index') }}">Retour à la liste</a>
        <br>
        {{ include('school/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/school/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}School{% endblock %}

{% block body %}
    <h1>School</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ school.id }}</td>
            </tr>
            <tr>
                <th>Nom de l'école</th>
                <td>{{ school.schoolName }}</td>
            </tr>
            <tr>
                <th>Adresse </th>
                <td>{{ school.schoolAddress1 }}</td>
            </tr>
            <tr>
                <th>Adresse (complément)</th>
                <td>{{ school.schoolAddress2 }}</td>
            </tr>
            <tr>
                <th>Code Postal</th>
                <td>{{ school.schoolZipCode }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ school.schoolCity }}</td>
            </tr>
            <tr>
                <th>Directeur/Directrice</th>
                <td>{{ school.schoolDirectorGender }}</td>
            </tr>
            <tr>
                <th>Nom du directeur/directrice</th>
                <td>{{ school.schoolDirectorName }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ school.schoolDirectorTel }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ school.schoolDirectorEmail }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('school_index') }}">Retour à la liste</a>

    <br>
    {% if app.session.get('user') %}
        {% for role in app.session.get('user').MemberRole %}
            {% if role.id ==  "6" %}
            <a href="{{ path('school_edit', {'id': school.id}) }}">Modifier</a>
            <br>
            {{ include('school/_delete_form.html.twig') }}
            {% endif %}
        {% endfor %}
    {% endif %}
    

{% endblock %}