src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $article_picture1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $article_picture2;

    // Picture 3 not used yet
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    // private $article_picture3;

    /**
     * @ORM\Column(type="float")
     */
    private $article_buttonValue;

    /**
     * @ORM\Column(type="float")
     */
    private $article_eurosValue;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $article_comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Color")
     */
    private $article_color;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Brand")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_brand;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Size")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_size;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\WearStatus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_wearStatus;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gender")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_gender;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProcessStatus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_processStatus;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Fabric", cascade={"persist"})
     */
    private $article_fabric;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DeliveryBag", inversedBy="deliveryBag_article_list")
     */
    private $article_deliveryBag;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DonationBag", inversedBy="donationBag_article_list")
     */
    private $article_donationBag;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Season")
     */
    private $article_season;

    /**
     * @ORM\Column(type="string", length=13)
     */
    private $article_code;


    public function __construct()
    {
        $this->article_color = new ArrayCollection();
        $this->article_fabric = new ArrayCollection();
        $this->article_season = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getArticlePicture1()
    {
        return $this->article_picture1;
    }

    public function setArticlePicture1( $article_picture1)  
    {
        $this->article_picture1 = $article_picture1;

        return $this;
    }

    public function getArticlePicture2()
    {
        return $this->article_picture2;
    }

    public function setArticlePicture2($article_picture2)
    {
        $this->article_picture2 = $article_picture2;

        return $this;
    }

    // Picture 3 not used yet
    // public function getArticlePicture3()
    // {
    //     return $this->article_picture3;
    // }

    // public function setArticlePicture3($article_picture3)
    // {
    //     $this->article_picture3 = $article_picture3;

    //     return $this;
    // }

    public function getArticleButtonValue(): ?float
    {
        return $this->article_buttonValue;
    }

    public function setArticleButtonValue(float $article_buttonValue): self
    {
        $this->article_buttonValue = $article_buttonValue;

        return $this;
    }

    public function getArticleEurosValue(): ?float
    {
        return $this->article_eurosValue;
    }

    public function setArticleEurosValue(float $article_eurosValue): self
    {
        $this->article_eurosValue = $article_eurosValue;

        return $this;
    }

    public function getArticleComments(): ?string
    {
        return $this->article_comments;
    }

    public function setArticleComments(?string $article_comments): self
    {
        $this->article_comments = $article_comments;

        return $this;
    }

    /**
     * @return Collection|Color[]
     */
    public function getArticleColor(): Collection
    {
        return $this->article_color;
    }

    public function addArticleColor(Color $articleColor): self
    {
        if (!$this->article_color->contains($articleColor)) {
            $this->article_color[] = $articleColor;
        }

        return $this;
    }

    public function removeArticleColor(Color $articleColor): self
    {
        if ($this->article_color->contains($articleColor)) {
            $this->article_color->removeElement($articleColor);
        }

        return $this;
    }

    public function getArticleBrand(): ?Brand
    {
        return $this->article_brand;
    }

    public function setArticleBrand(?Brand $article_brand): self
    {
        $this->article_brand = $article_brand;

        return $this;
    }

    public function getArticleType(): ?Type
    {
        return $this->article_type;
    }

    public function setArticleType(?Type $article_type): self
    {
        $this->article_type = $article_type;

        return $this;
    }

    public function getArticleSize(): ?Size
    {
        return $this->article_size;
    }

    public function setArticleSize(?Size $article_size): self
    {
        $this->article_size = $article_size;

        return $this;
    }

    public function getArticleWearStatus(): ?WearStatus
    {
        return $this->article_wearStatus;
    }

    public function setArticleWearStatus(?WearStatus $article_wearStatus): self
    {
        $this->article_wearStatus = $article_wearStatus;

        return $this;
    }

    public function getArticleGender(): ?Gender
    {
        return $this->article_gender;
    }

    public function setArticleGender(?Gender $article_gender): self
    {
        $this->article_gender = $article_gender;

        return $this;
    }

    public function getArticleProcessStatus(): ?ProcessStatus
    {
        return $this->article_processStatus;
    }

    public function setArticleProcessStatus(?ProcessStatus $article_processStatus): self
    {
        $this->article_processStatus = $article_processStatus;

        return $this;
    }

    /**
     * @return Collection|Fabric[]
     */
    public function getArticleFabric(): Collection
    {
        return $this->article_fabric;
    }

    public function addArticleFabric(Fabric $articleFabric): self
    {
        if (!$this->article_fabric->contains($articleFabric)) {
            $this->article_fabric[] = $articleFabric;
        }

        return $this;
    }

    public function removeArticleFabric(Fabric $articleFabric): self
    {
        if ($this->article_fabric->contains($articleFabric)) {
            $this->article_fabric->removeElement($articleFabric);
        }

        return $this;
    }

    public function getArticleDeliveryBag(): ?DeliveryBag
    {
        return $this->article_DeliveryBag;
    }

    public function setArticleDeliveryBag(?DeliveryBag $article_DeliveryBag): self
    {
        $this->article_DeliveryBag = $article_DeliveryBag;

        return $this;
    }

    public function getArticleDonationBag(): ?DonationBag
    {
        return $this->article_donationBag;
    }

    public function setArticleDonationBag(?DonationBag $article_donationBag): self
    {
        $this->article_donationBag = $article_donationBag;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getArticleSeason(): Collection
    {
        return $this->article_season;
    }

    public function addArticleSeason(Season $articleSeason): self
    {
        if (!$this->article_season->contains($articleSeason)) {
            $this->article_season[] = $articleSeason;
        }

        return $this;
    }

    public function removeArticleSeason(Season $articleSeason): self
    {
        if ($this->article_season->contains($articleSeason)) {
            $this->article_season->removeElement($articleSeason);
        }

        return $this;
    }

    public function getArticleCode(): ?string
    {
        return $this->article_code;
    }

    public function setArticleCode(?string $last_article_code): ?string
    {
        // We get a NUM code from the 4 last characters of the last similar article
        $numCode = substr( $last_article_code, -4 );

        // We increment this NUM code  
        if( ctype_digit($numCode) ) {
            $numCode = (int)$numCode;
            $numCode++;
            $numCode=str_pad($numCode,4,"0",STR_PAD_LEFT);
        }
       // We create a GENDER code
        $genderCode = $this->getArticleGender()->getGenderCode();
        
        // We create a SIZE code
        $sizeCode = $this->getArticleSize()->getSizeCode();

        // We create a SEASON code ( with 1 or 2 optionnal characters)
        $seasonCode='';
            foreach($this->getArticleSeason() as $articleSeason)
            {
                $seasonCode = $seasonCode.$articleSeason->getSeasonCode();
            }
        if(strlen($seasonCode)<1)
            {
                $seasonCode= ( str_pad($seasonCode ,2, "0", STR_PAD_LEFT) );
            }
        // We create a TYPE code
        $typeCode = $this->getArticleType()->getTypeCode();

        // We concatenate the differents codes
        $this->article_code = $genderCode.$sizeCode.$seasonCode.$typeCode.$numCode;
        
        return $this->article_code;
    }

}

src/Entity/Brand.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BrandRepository")
 */
class Brand
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $brand_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $brand_code;

    public function getId()
    {
        return $this->id;
    }

    public function getBrandName(): ?string
    {
        return $this->brand_name;
    }

    public function setBrandName(string $brand_name): self
    {
        $this->brand_name = $brand_name;

        return $this;
    }

    public function getBrandCode(): ?string
    {
        return $this->brand_code;
    }

    public function setBrandCode(?string $brand_code): self
    {
        $this->brand_code = $brand_code;

        return $this;
    }
}

src/Entity/Kid.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\KidRepository")
 */
class Kid
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank()
    */
    private $kid_name;

    /**
    * @ORM\Column(type="string", length=255)
    * @Assert\NotBlank()
    */
    private $kid_surname;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\NotBlank()
     * @Assert\Type("\DateTime")
     */
    private $kid_birthday;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\School", inversedBy="school_kid_list")
     */
    private $kid_school_id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Member", mappedBy="member_kid_list", cascade={"persist"})
     * @Assert\NotBlank()
     */
    private $kid_parent_list;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gender")
     * @ORM\JoinColumn(nullable=false)
     */
    private $kid_gender;

    public function __construct()
    {
        $this->kid_parent_list = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getKidName(): ?string
    {
        return $this->kid_name;
    }

    public function setKidName(string $kid_name): self
    {
        $this->kid_name = $kid_name;

        return $this;
    }

    public function getKidSurname(): ?string
    {
        return $this->kid_surname;
    }

    public function setKidSurname(string $kid_surname): self
    {
        $this->kid_surname = $kid_surname;

        return $this;
    }

    public function getKidBirthday(): ?\DateTimeInterface
    {
        return $this->kid_birthday;
    }

    public function setKidBirthday(?\DateTimeInterface $kid_birthday): self
    {
        $this->kid_birthday = $kid_birthday;

        return $this;
    }

    public function getKidSchoolId(): ?School
    {
        return $this->kid_school_id;
    }

    public function setKidSchoolId(?School $kid_school_id): self
    {
        $this->kid_school_id = $kid_school_id;

        return $this;
    }

    /**
     * @return Collection|Member[]
     */
    public function getKidParentList(): Collection
    {
        return $this->kid_parent_list;
    }

    public function addKidParentList(Member $kidParentList): self
    {
        if (!$this->kid_parent_list->contains($kidParentList)) {
            $this->kid_parent_list[] = $kidParentList;
            $kidParentList->addMemberKidList($this);
        }

        return $this;
    }

    public function setKidParentList(Member $kidParentList): self
    {
        return $this->addKidParentList($kidParentList);
    }

    public function removeKidParentList(Member $kidParentList): self
    {
        if ($this->kid_parent_list->contains($kidParentList)) {
            $this->kid_parent_list->removeElement($kidParentList);
            $kidParentList->removeMemberKidList($this);
        }

        return $this;
    }

    public function getKidGender(): ?Gender
    {
        return $this->kid_gender;
    }

    public function setKidGender(?Gender $kid_gender): self
    {
        $this->kid_gender = $kid_gender;

        return $this;
    }

    public function getKidAge()
    {
        $dateInterval = $this->kid_birthday->diff(new \DateTime());
        $age=(($dateInterval->y)*12)+ ($dateInterval->m);
 
        return $age;
    }

        public function getKidSizeCode()
    {
        if ($this->getKidAge()<12)
        {
            $sizeCode=(str_pad($this->getKidAge(),2,"0",STR_PAD_LEFT)).'M';
        }
        if ($this->getKidAge()>12)
        {
            $sizeCode=(str_pad(floor($this->getKidAge()/12),2,"0",STR_PAD_LEFT)).'A';
        }
        return $sizeCode;
    }

}

src/Entity/Size.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SizeRepository")
 */
class Size
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $size_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $size_code;

    public function getId()
    {
        return $this->id;
    }

    public function getSizeName(): ?string
    {
        return $this->size_name;
    }

    public function setSizeName(string $size_name): self
    {
        $this->size_name = $size_name;

        return $this;
    }

    public function getSizeCode(): ?string
    {
        return $this->size_code;
    }

    public function setSizeCode(string $size_code): self
    {
        $this->size_code = $size_code;

        return $this;
    }
}

src/Entity/Type.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TypeRepository")
 */
class Type
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_code;

    public function getId()
    {
        return $this->id;
    }

    public function getTypeName(): ?string
    {
        return $this->type_name;
    }

    public function setTypeName(string $type_name): self
    {
        $this->type_name = $type_name;

        return $this;
    }

    public function getTypeCode(): ?string
    {
        return $this->type_code;
    }

    public function setTypeCode(string $type_code): self
    {
        $this->type_code = $type_code;

        return $this;
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un article{% endblock %}

{% block body %}
    <div class="container">
        
            <h1>Article à modifier</h1>

            <form class="form-group" method="post">
            {{ include('article/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
            </form>

            <a href="{{ path('article_index') }}">Retour à la liste</a>

            {{ include('article/_delete_form.html.twig') }}
        
    </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles{% endblock %}

{% block body %}
    <h1>Liste des articles</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Sexe</th>
                <th>Catégorie</th>
                <th>Saison</th>
                <th>Taille</th>
                <th>Marque</th>
                <th>Photo 1</th>
                <th>Valeur (boutons)</th>
                <th>Valeur (euros)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.articleGender.GenderName }}</td>
                <td>{{ article.articleType.TypeName }}</td>
                <td>
                {% for season in article.articleSeason %}
                {{ season.SeasonName }}
                {% endfor %}
                </td>
                <td>{{ article.articleSize.SizeName }}</td>
                <td>{{ article.articleBrand.BrandName }}</td>
                <td>{{ article.articlePicture1 }}</td>
                <td>{{ article.articleButtonValue }}</td>
                <td>{{ article.articleEurosValue }}</td>
                <td>
                    <a href="{{ path('article_show', {'id': article.id}) }}">voir - </a>
                    <a href="{{ path('article_edit', {'id': article.id}) }}"> modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Aucun article trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('article_new') }}">Créer un nouvel article</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création Article{% endblock %}

{% block body %}
    <div class="container">
        <h1>Créer un nouveau article</h1>
        <form class="form-group" method="post">
        {{ include('article/_form.html.twig', {'button_label': 'Créer'}) }}
        </form>
        <a href="{{ path('article_index') }}">Retour à la liste</a>
    </div>
{% endblock %}

templates/article/selection.html.twig
{% extends 'base.html.twig' %}

{% block title %}Je trouve{% endblock %}

{% block body %}

<div class="container">
    <h1>Je trouve</h1>
    <p>Grâce à vos points sur votre cagnotte et 1€ par vêtement, ou bien pour quelques €, achetez des vêtements de seconde main, en parfait état ! </p>

        <div class="row">
            <div class="col-md-3">
                {% if app.session.get('user') %}
                    <h2>Préselection</h2>
                    <form action="/article/selection" method="post" class="form-group">
                    <select name="preselectionKid" id="preselectionKid" class="form-control dropdown">
                        {% for kid in app.session.get('user').memberKidList %}
                            {% if kid.kidAge > 12 %}
                            {% set age=(kid.kidAge/12) %}
                            <option value="{{kid.id}}">Sélection pour {{kid.kidSurname}} - {{age|round}} ans - Taille {{kid.kidSizeCode}}</option>
                            {% else %} #}
                            <option value="{{kid.id}}">Sélection pour {{kid.kidSurname}} - {{kid.kidAge}} mois - Taille {{kid.kidSizeCode}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    <br>
                    <input type="submit" value="VOIR">
                    <br>
                    </form>
                {% endif %}
                <h2>Filtres</h2>
                <form action="/article/selection" method="post" class="form-group">
                    {# A FINIR
                    Voir comment transformer les selects en dropdown choix multiple #}
                    <label for="selectionGender">Sexe(s)</label>
                    <select name="selectionGender[]" id="selectionGender" class="form-control mdb-select">
                        {% for gender in genders %}
                        <option value="{{gender.id}}">{{gender.genderName}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <label for="selectionSize">Taille(s)</label>
                    <select name="selectionSize[]" id="selectionSize" multiple="true" expanded="false" class="form-control mdb-select">
                        {% for size in sizes %}
                        <option value="{{size.id}}">{{size.sizeName}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <label for="selectionType">Type(s) de vêtement</label>
                    <select name="selectionType[]" id="selectionType" multiple="multiple" class="form-control mdb-select">
                        {% for type in types %}
                        <option value="{{type.id}}">{{type.typeName}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <label for="selectionSeason">Saison(s)</label>
                    <select name="selectionSeason[]" id="selectionSeason" multiple="multiple" class="form-control mdb-select">
                        {% for season in seasons %}
                        <option value="{{season.id}}">{{season.seasonName}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <label for="selectionColor">Couleur(s)</label>
                    <select name="selectionColor[]" id="selectionColor" multiple="multiple" class="form-control mdb-select">
                        {% for color in colors %}
                        <option value="{{color.id}}">{{color.colorName}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <label for="selectionBrand">Marque(s)</label>
                    <select name="selectionBrand[]" id="selectionBrand" multiple="multiple" class="form-control mdb-select">
                        {% for brand in brands %}
                        <option value="{{brand.id}}">{{brand.brandName}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <label for="selectionWearStatus">Etat usure(s)</label>
                    <select name="selectionWearStatus[]" id="selectionWearStatus" multiple="multiple" class="form-control mdb-select">
                        {% for wearStatus in wearStatuss %}
                        <option value="{{wearStatus.id}}">{{wearStatus.wearStatusName}}</option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="FILTRER">
                    <br>
                </form>
                <a href="{{path('article_selection')}}">Revoir tout le catalogue </a>
            </div>
            <br> 
            <div class="col-md-9">
                <h1>Liste des articles</h1>
                    <div class="row">
                        {% for article in articles %}
                        <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
                            <div class="card h-100">
                                <a href="#"><img class="card-img-top" src="{{ asset('uploads/pictures/' ~ article.articlePicture1)}}" alt=""></a>
                                <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{{ path('article_show', {'id': article.id}) }}">{{ article.articleType.TypeName }} - {{ article.articleGender.GenderName }} - {{ article.articleSize.SizeName }}</a>
                                </h5>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <p>Aucun article trouvé</p>
                        {% endfor %}
                    </div>
            </div>
        </div>
</div>
{% endblock %}

{% block javascripts %}

    <!--[if lt IE 9]>
    <script type="text/javascript" src="assets/js/jquery-1.12.4.min.js"></script>
    <![endif]-->
    <!--[if gte IE 9]><!-->
    <script type="text/javascript" src="http://127.0.0.1:8000/vendor/jquery/jquery-3.3.1.min.js"></script>
    <!--<![endif]-->
{# NE FONCTIONNE PAS #}
    <script>
        $(document).ready(function() {
            $('.mdb-select').material_select();
         });
    
    </script>
{% endblock %}

    {# <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> #}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        {# <h1 class="mt-4 mb-3">Portfolio Item
            <small>Subheading</small>
        </h1> #}
        <br>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            <a href="{{ path('home_show') }}">Accueil</a>
            </li>
            <li class="breadcrumb-item active">
            <a href="{{ path('article_selection') }}">Ma sélection</a>
            </li>
        </ol>

        <!-- Portfolio Item Row -->
        <div class="row h-100">
            <div class="col-md-6">
                {# <div class="col-md-8">
                <img class="img-fluid" src="{{ asset('uploads/pictures/' ~ article.articlePicture1)}}" alt="{{ article.articlePicture1 }}">
                </div> #}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                        <img class="d-block w-100 img-fluid" src="{{ asset('uploads/pictures/' ~ article.articlePicture1)}}" alt="First slide">
                        </div>
                        <div class="carousel-item">
                        <img class="d-block w-100 img-fluid" src="{{ asset('uploads/pictures/' ~ article.articlePicture2)}}" alt="Second slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <h2 class="my-3">{{ article.articleType.typeName }} {{ article.articleGender.genderName }} {{ article.articleSize.sizeName }}</h2>
                    <p>{{ article.articleComments }}</p>
                <h4 class="my-3">Détails</h4>
                <table>
                    <tbody align="left">
                        <tr>
                            <th>Marque</th>
                            <td>{{ article.articleBrand.brandName }}</td>
                        </tr>
                        <tr>
                            <th>Saison</th>
                            {% for season in article.articleSeason %}
                            <td>{{ season.seasonName }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Couleur(s)</th>
                            {% for color in article.articleColor %}
                            <td>{{ color.colorName }}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            <th>Valeur (boutons)</th>
                            <td>{{ article.articleButtonValue }}</td>
                        </tr>
                        <tr>
                            <th>Valeur (euros)</th>
                            <td>{{ article.articleEurosValue }}</td>
                        </tr>
                    </tbody>
                </table>
                <div>
                    <a href="{{ path('delivery_bag_addToCart', {'id': article.id}) }}" class="btn btn-primary">Ajouter au panier</a>
                </div>
            </div>
      </div>
      <!-- /.row -->
        <br>
        <b>
    </div>
    <!-- /.container -->

    {% if app.session.get('user') %}
        {% for role in app.session.get('user').MemberRole %}
            {% if role.id ==  "6" %}
                 <div display="inline-block">
            <a href="{{ path('article_index') }}">Liste de tous les articles</a>
            <p> - </p>
            <a href="{{ path('article_edit', {'id': article.id}) }}">Modifier</a>
            <p> - </p>
            <a href="{{ path('article_delete', {'id': article.id}) }}">Supprimer</a>
        </div>
            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock %}


    